language: node_js
node_js:
- stable

notifications:
  slack:
    secure: Na0fYOFQCfjlECaJI188ePkVzWjR6uekBCLHeWw5NjiS4Coonzz9o1TTChd1Orby3+Td1zKaIQBDZc1Lva0TdM9akiYsVeCsmCO8XN8fG1TJeMHOqg+/cfzJ1GO9gKAzRuxtVCUx+dk7bEo/3WjVAD+BPMpHIxNYUbrjdNX+oNjFDPFvFxi6bzopHPgCUGhri4jQr7c0wBp3S+8teU59+El/LjSXLSOLUPWdkSL5BYa8Uklazib+V5v+n4HHizePBBwNTFj0KUb/UVPWoqWBx+5Y1+rw6ZGVUjCyHdrqbEgyRqo3yZ0Lkz57NTLgB1eiUcmYGqkkXgjWmT9O5ksSaiGgsg5/8waQfsjXtm8TglqF8jccwxIBtEgWgWZ8q+6SSwJEqkhU3yLzaEgHvsKxU8M+WcaebPId7KtVf+fbRUPTM2qAizHohW8BEdsXajmYghMp+AvJzOuf0AIkxlCi9aQzn1O0upfXnJsY5ktJCM/i1++Z0HfueBkgmCS5D63KhLpSaoEP6nDzEuMreLy0mg+e7BmAEiXoKPdHPkBvFPvuNaJHWcnsxUvK3RJLIUSAnEwTl7MvFA73O2LlCy0p7BHnPrmbveHK2WMtbjb4Gn2RMbiZBhCCctmYn/UMs06e8avNpkyTfA49q/hxZs0qimeDds5vB8f0B+AYMmbJyF0=
